FROM golang:1.12.1-stretch 
# FROM golang:1.12.1-alpine 
LABEL maintainer="RGRU <ivlev@rg.ru>"

RUN apt-get -y update && apt-get -y install sshpass 



# COPY configs  /app/configs
# COPY migrations  /app/migrations
# COPY templates  /app/templates
# COPY docs  /app/docs
# COPY onlinebc_admin  /app/onlinebc
# 
# ENV RUNNING_IN_DOCKER="Y"
# EXPOSE 7700
# CMD bash -c "cd /app && ./onlinebc -serve 7700"


WORKDIR /go/src/app
COPY . .

# RUN go get -d -v ./...
# RUN go install -v ./...
# or
RUN go get ./...
RUN env CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a  . 

CMD ["app", "-serve", "7700"]

