version: '3.1'

services:

  db:
    image: postgres
    container_name: onlinebc-db
    restart: always
    # ports:
    #   - 5432:5432
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: onlinebc 
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
      image: redis
      container_name: onlinebc-redis
      # ports:
      #     - "6389:6379"
      restart: always

  runner:
    image: vadimivlev/onlinebc
    container_name: onlinebc-runner
    restart: always
    # расскомментируйте следующую строку если хотите полное API
    # command: bash -c "sleep 10 && cd /app && ./onlinebc -serve 7700"
    ports:
      - 7700:7700
    depends_on:
      - db
      - redis
    links:
      - db
      - redis



# Расскомментируйте если хотите просматривать базу данных в браузере http://localhost:8080

  # adminer:
  #   image: adminer
  #   container_name: adminer-com
  #   # network_mode: bridge
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  #   links:
  #     - db

