version: '3.1'

services:

  db:
    image: postgres
    container_name: psql-com
    # network_mode: bridge
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"
      - "./migrations:/dumps"
      - "./etc/.pgpass:/root/.pgpass"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: onlinebc 
      PGDATA: /var/lib/postgresql/data/pgdata


  redis:
      image: redis
      container_name: pg-redis-com
      # network_mode: bridge
      ports:
          - "6389:6379"
      restart: always


  adminer:
    image: adminer
    container_name: adminer-com
    # network_mode: bridge
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db


  runner:
    image: debian:7.11-slim
    container_name: runner
    # network_mode: bridge
    environment:
      RUNNING_IN_DOCKER: Y
    restart: always
    command: bash -c "cd /app && ./onlinebc -serve 7700 -front"
    ports:
      - 7700:7700
    volumes:
      - ".:/app"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis


