version: '3.1'

services:

  db:
    image: postgres
    container_name: onlinebc-db
    restart: always
    # ports:
    #   - 5432:5432
    # volumes:
    #   - "./pgdata:/var/lib/postgresql/data/pgdata"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: onlinebc 
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
      image: redis
      container_name: onlinebc-redis
      # ports:
      #     - "6389:6379"
      restart: always

  # сервер для загрузки изображений по ssh
  imgserver:
    image: sickp/alpine-sshd
    container_name: onlinebc-imgserver
    volumes:
     - ./uploads:/var/www/onlinebc/uploads
    # ports:
    #  - "222:22"
    restart: always

  runner:
    image: rgru/onlinebc_admin
    container_name: onlinebc-runner
    restart: always
    # расскомментируйте следующую строку если хотите доступ только к публичному REST API 
    # command: bash -c "cd /app && ./onlinebc -serve 7700 -front"
    ports:
      - 7700:7700
    depends_on:
      - db
      - redis
      - imgserver
    links:
      - db
      - redis
      - imgserver



# Расскомментируйте если хотите просматривать базу данных в браузере http://localhost:8080

  # adminer:
  #   image: adminer
  #   container_name: adminer-com
  #   # network_mode: bridge
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - db
  #   links:
  #     - db

