dev:
  connection string:      127.0.0.1:6389
  time to live:           30  


docker:
  connection string:      redis:6379
  time to live:           30    


prod:
  connection string:      127.0.0.1:6389
  time to live:           30  

