
# COMMON ====================================================================================================================
# COMMON ====================================================================================================================
# COMMON ====================================================================================================================
# COMMON ====================================================================================================================




# Общие ---------------------------------------------------

- comment: Стартовая страница
  methods: [GET]
  path: /
  example: /
  controller: LandingPage

- comment: JSON  маршрутов.  Документация API.
  methods: [GET]
  path: /routes
  example: /routes
  controller: GetRoutes





# FRONTEND ====================================================================================================================
# FRONTEND ====================================================================================================================
# FRONTEND ====================================================================================================================
# FRONTEND ====================================================================================================================



# Фронтэнд ---------------------------------------------------  


- comment: Список трансляций
  methods: [GET]
  path: /api/broadcasts
  example: /api/broadcasts
  controller: GetBroadcasts

- comment: Трасляция с идентификатором id и ее постами
  methods: [GET]
  path: /api/full-broadcast/:id
  example: /api/full-broadcast/354
  controller: GetFullBroadcast

- comment: Посты трансляции с идентификатором id
  methods: [GET]
  path: /api/posts/:id
  example: /api/posts/354
  controller: GetPosts

- comment: Ответы к посту с идентификатором id
  methods: [GET]
  path: /api/answers/:id
  example: /api/answers/23932
  controller: GetAnswers

- comment: Медиа для поста с идентификатором id
  methods: [GET]
  path: /api/media/:id
  example: /api/media/23932
  controller: GetMedia

- comment: Трасляция с идентификатором id и ее постами. Legacy
  methods: [GET]
  path: /api/online.php
  example: /api/online.php
  controller: GetFullBroadcastLegacy
  params:
  - comment: Идентификатор трансляции
    name: id
    inptype : number
    value: ':id'
    test: 354

- comment: Список трансляций.Legacy
  methods: [GET, HEAD]
  path: /api/
  example: /api/?main=0&active=0&num=3
  controller: GetBroadcastList
  params:
  - comment: Основная {0|1}
    name: main
    inptype : number
    value: '{main}'
    test: 0
  - comment: Активность {0|1}
    name: active
    inptype : number
    value: '{active}'
    test: 0
  - comment: Номер
    name: num
    inptype : number
    value: '{num}'
    test: 3