# Бэкэнд ----------------------------------------------------

#  media ---------------------------------------------------


- comment   : Получить Медиа с идентификатором id
  methods   :
  - GET
  path      : /medium/{id}
  example   : /medium/5330
  controller: GetMedium

- comment: Создать медиа поста с идентификатором post_id
  methods: 
  - GET
  - POST
  path: /create-medium/
  example: /create-medium/
  controller: CreateMedium
  params    :
  - comment: идентификатор поста
    name   : post_id
    value  : '{post_id}'
    test   : 23932
  - comment: URI изображения
    name   : uri
    value  : '{uri}'
    test   : created_image.jpg
  - comment: Уменьшенное изображение
    name   : thumb
    value  : '{thumb}'
    test   : created_thumb.jpg
  - comment: Источник
    name   : source
    value  : '{source}'
    test   : новый телевизор



- comment   : Редактировать Медиа с идентификатором id
  methods   : 
  - POST 
  - PUT
  path      : /update-medium/{id}
  example   : 
  controller: UpdateMedium
  params    :
  - comment: идентификатор поста
    name   : post_id
    value  : '{post_id}'
    test   : 23932
  - comment: URI изображения
    name   : uri
    value  : '{uri}'
    test   : updated_image.jpg
  - comment: Уменьшенное изображение
    name   : thumb
    value  : '{thumb}'
    test   : updated_thumb.jpg
  - comment: Источник
    name   : source
    value  : '{source}'
    test   : updated телевизор


- comment: Удалить Медиа с идентификатором id
  methods: 
  - POST
  - DELETE
  path: /delete-medium/{id}
  example: /delete-medium/5330
  controller: DeleteMedium


# post ------------------------------------------------------------


- comment   : Получить пост с идентификатором id
  methods   : 
  - GET
  path      : /post/{id}
  example   : /post/23932
  controller: GetPost


- comment: Создать пост трансляции с идентификатором id
  methods: [POST]
  path: /post/{id}
  example: /post/23932
  controller: GetPost


- comment   : Редактировать Пост с идентификатором id
  methods   : [PUT,GET]
  path      : /update-post/{id}
  example   : /update-post/23932
  controller: UpdatePost
  params    :
  - comment : Идентификатор поста если это ответ
    name    : id_parent
    value   : '{id_parent}'
    test    : 0
  - comment : Идентификатор трансляции
    name    : id_broadcast
    value   : '{id_broadcast}'
    test    : 354
  - comment : Текст поста
    name    : text
    value   : '{text}'
    test    : Текст поста
  - comment : Время поста в формате UNIX
    name    : post_time
    value   : '{post_time}'
    test    : 1528376820
  - comment : Тип поста 1,2,3,4...
    name    : post_type
    value   : '{post_type}'
    test    : 3
  - comment : Ссылка
    name    : link
    value   : '{link}'
    test    : http://google.com
  - comment : Есть ли большое изображение 0,1
    name    : has_big_img
    value   : '{has_big_img}'
    test    : 0
  - comment : ФИО автора поста
    name    : author
    test    : Сидор Пупкин
    value   : '{author}'



- comment: Удалить Пост с идентификатором id
  methods: [DELETE]
  path: /post/{id}
  example: /post/23932
  controller: GetPost




#  broadcast ---------------------------------------------------

- comment   : Получить трансляцию с идентификатором id
  methods   : [GET]
  path      : /broadcast/{id}
  example   : /broadcast/354
  controller: GetBroadcast


- comment: Создать трансляцию
  methods: [POST]
  path: /broadcast/{id}
  example: /broadcast/354
  controller: GetBroadcast

 
- comment: Редактировать трансляцию с идентификатором id
  methods:
  - PUT
  path: /broadcast/{id}
  example: /broadcast/354
  controller: GetBroadcast

 
- comment: Удалить трансляцию с идентификатором id
  methods: [DELETE]
  path: /broadcast/{id}
  example: /broadcast/354
  controller: GetBroadcast

# Общие ---------------------------------------------------

- comment: Стартовая страница
  methods: [GET, HEAD]
  path: /
  example: /
  controller: LandingPage

- comment: JSON  маршрутов.  Документация API.
  methods: [GET, HEAD]
  path: /routes
  example: /routes
  controller: GetRoutes


# Фронтэнд ---------------------------------------------------  


- comment: Список трансляций
  methods: [GET, HEAD]
  path: /broadcasts
  example: /broadcasts
  controller: GetBroadcasts

- comment: Трасляция с идентификатором id и ее постами
  methods: [GET, HEAD]
  path: /full-broadcast/{id}
  example: /full-broadcast/354
  controller: GetFullBroadcast

- comment: Посты трансляции с идентификатором id
  methods: [GET, HEAD]
  path: /posts/{id}
  example: /posts/354
  controller: GetPosts

- comment: Ответы к посту с идентификатором id
  methods: [GET, HEAD]
  path: /answers/{id}
  example: /answers/23932
  controller: GetAnswers

- comment: Медиа записи поста с идентификатором id
  methods: [GET, HEAD]
  path: /media/{id}
  example: /media/23932
  controller: GetMedia

- comment: Трасляция с идентификатором id и ее постами. Legacy
  methods: [GET, HEAD]
  path: /api/online.php
  example: /api/online.php?id=354
  controller: GetFullBroadcast
  params:
  - comment: Идентификатор трансляции
    name: id
    value: '{id}'

- comment: Список трансляций.Legacy
  methods: [GET, HEAD]
  path: /api/
  example: /api/?main=0&active=0&num=3
  controller: GetBroadcastList
  params:
  - comment: Основная {0|1}
    name: main
    value: '{main}'
  - comment: Активность {0|1}
    name: active
    value: '{active}'
  - comment: Номер
    name: num
    value: '{num}'