# Бэкэнд ----------------------------------------------------


# GraphQL --------------------------------------------------

- comment   : GraphQL запрос
  methods   :
  - post
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : >- 
      { 
        songs 
          { 
            title,  
            duration 
          }
      }





#  media ---------------------------------------------------


- comment   : Получить Медиа с идентификатором id
  methods   :
  - GET
  path      : /medium/{id}
  example   : /medium/5330
  controller: GetMedium

- comment: Создать медиа поста с идентификатором post_id
  methods: 
  # - GET
  - POST
  path: /create-medium/
  example: /create-medium/
  controller: CreateMedium
  params    :
  - comment: идентификатор поста
    name   : post_id
    value  : '{post_id}'
    test   : 23932
  - comment: URI изображения
    name   : uri
    value  : '{uri}'
    test   : created_image.jpg
  - comment: Уменьшенное изображение
    name   : thumb
    value  : '{thumb}'
    test   : created_thumb.jpg
  - comment: Источник
    name   : source
    value  : '{source}'
    test   : новый телевизор



- comment   : Редактировать Медиа с идентификатором id
  methods   : 
  - GET
  - PUT
  path      : /update-medium/{id}
  example   : /update-medium/5330
  controller: UpdateMedium
  params    :
  - comment: идентификатор поста
    name   : post_id
    value  : '{post_id}'
    test   : 23932
  - comment: URI изображения
    name   : uri
    value  : '{uri}'
    test   : updated_image.jpg
  - comment: Уменьшенное изображение
    name   : thumb
    value  : '{thumb}'
    test   : updated_thumb.jpg
  - comment: Источник
    name   : source
    value  : '{source}'
    test   : updated телевизор


- comment   : Удалить Медиа с идентификатором id
  methods   : 
  - GET
  - DELETE
  path      : /delete-medium/{id}
  example   : /delete-medium/5389
  controller: DeleteMedium



# post ------------------------------------------------------------


- comment   : Получить пост с идентификатором id
  methods   : 
  - GET
  path      : /post/{id}
  example   : /post/23932
  controller: GetPost


- comment: Создать пост трансляции с идентификатором id
  methods:
  - GET
  - POST
  path: /create-post/
  example: /create-post/
  controller: CreatePost
  params    :
  - comment : Идентификатор поста если это ответ
    name    : id_parent
    value   : '{id_parent}'
    test    : 0
  - comment : Идентификатор трансляции
    name    : id_broadcast
    value   : '{id_broadcast}'
    test    : 354
  - comment : Текст поста
    name    : text
    value   : '{text}'
    test    : Текст поста
  - comment : Время поста в формате UNIX
    name    : post_time
    value   : '{post_time}'
    test    : 1528376820
  - comment : Тип поста 1,2,3,4...
    name    : post_type
    value   : '{post_type}'
    test    : 3
  - comment : Ссылка
    name    : link
    value   : '{link}'
    test    : http://google.com
  - comment : Есть ли большое изображение 0,1
    name    : has_big_img
    value   : '{has_big_img}'
    test    : 0
  - comment : ФИО автора поста
    name    : author
    test    : Сидор Пупкин
    value   : '{author}'



- comment   : Редактировать Пост с идентификатором id
  methods   : 
  - GET
  - PUT
  path      : /update-post/{id}
  example   : /update-post/30001
  controller: UpdatePost
  params    :
  - comment : Идентификатор поста если это ответ
    name    : id_parent
    value   : '{id_parent}'
    test    : 
  - comment : Идентификатор трансляции
    name    : id_broadcast
    value   : '{id_broadcast}'
    test    : 354
  - comment : Текст поста
    name    : text
    value   : '{text}'
    test    : Текст поста
  - comment : Время поста в формате UNIX
    name    : post_time
    value   : '{post_time}'
    test    : 1528376820
  - comment : Тип поста 1,2,3,4...
    name    : post_type
    value   : '{post_type}'
    test    : 3
  - comment : Ссылка
    name    : link
    value   : '{link}'
    test    : http://google.com
  - comment : Есть ли большое изображение 0,1
    name    : has_big_img
    value   : '{has_big_img}'
    test    : 0
  - comment : ФИО автора поста
    name    : author
    test    : Сидор Пупкин
    value   : '{author}'



- comment   : Удалить Пост с идентификаторомid
  methods   :
  - GET
  - DELETE
  path      : /delete-post/{id}
  example   : /delete-post/30001
  controller: DeletePost




#  broadcast ---------------------------------------------------

- comment   : Получить трансляцию с идентификатором id
  methods   : 
  - GET
  path      : /broadcast/{id}
  example   : /broadcast/354
  controller: GetBroadcast


- comment: Создать трансляцию
  methods: 
  - GET
  - POST
  path: /create-broadcast/
  example: /create-broadcast/
  controller: CreateBroadcast
  params    :
  - comment : Название трансляции
    name    : title
    value   : '{title}'
    test    : Новая трансляция
  - comment : Время создания
    name    : time_created
    value   : '{time_created}'
    test    : 1528376820
  - comment : Время начала
    name    : time_begin
    value   : '{time_begin}'
    test    : 1528376820
  - comment : Завершена 0 1
    name    : is_ended
    value   : '{is_ended}'
    test    : 1
  - comment : Показывать дату 0 1
    name    : show_date
    value   : '{show_date}'
    test    : 1
  - comment : Показывать время 0 1
    name    : show_time
    value   : '{show_time}'
    test    : 0
  - comment : Яндекс трансляция 0 1
    name    : is_yandex
    value   : '{is_yandex}'
    test    : 
  - comment : Идентификаторы Яндекс трансляций
    name    : yandex_ids
    value   : '{yandex_ids}'
    test    : 2, 333, 555
  - comment : Показывать на главной странице 0 1
    name    : show_main_page
    value   : '{show_main_page}'
    test    : 0
  - comment : Ссылка
    name    : link_article
    value   : '{link_article}'
    test    : http://www.rg.ru/2013/08/09/zhrebiy-site-anons.html
  - comment : Ссылка на изображение
    name    : link_img
    value   : '{link_img}'
    test    : //cdnimg.rg.ru/pril/article/126/55/62/lukjanov-zavrazhin100.jpg
  - comment : groups_create
    name    : groups_create
    value   : '{groups_create}'
    test    : 0
  - comment : Дневник 0 1
    name    : is_diary
    value   : '{is_diary}'
    test    : 0
  - comment : Автор Дневника
    name    : diary_author
    value   : '{diary_author}'
    test    : Новиков 

 
- comment: Редактировать трансляцию с идентификатором id
  methods:
  - GET
  - PUT
  path: /update-broadcast/{id}
  example: /update-broadcast/354
  controller: UpdateBroadcast
  params    :
  - comment : Название трансляции
    name    : title
    value   : '{title}'
    test    : Обновленная трансляция
  - comment : Время создания
    name    : time_created
    value   : '{time_created}'
    test    : 1528376820
  - comment : Время начала
    name    : time_begin
    value   : '{time_begin}'
    test    : 1528376820
  - comment : Завершена 0 1
    name    : is_ended
    value   : '{is_ended}'
    test    : 1
  - comment : Показывать дату 0 1
    name    : show_date
    value   : '{show_date}'
    test    : 1
  - comment : Показывать время 0 1
    name    : show_time
    value   : '{show_time}'
    test    : 0
  - comment : Яндекс трансляция 0 1
    name    : is_yandex
    value   : '{is_yandex}'
    test    : 
  - comment : Идентификаторы Яндекс трансляций
    name    : yandex_ids
    value   : '{yandex_ids}'
    test    : 2, 333, 555
  - comment : Показывать на главной странице 0 1
    name    : show_main_page
    value   : '{show_main_page}'
    test    : 0
  - comment : Ссылка
    name    : link_article
    value   : '{link_article}'
    test    : http://www.rg.ru/2013/08/09/zhrebiy-site-anons.html
  - comment : Ссылка на изображение
    name    : link_img
    value   : '{link_img}'
    test    : //cdnimg.rg.ru/pril/article/126/55/62/lukjanov-zavrazhin100.jpg
  - comment : groups_create
    name    : groups_create
    value   : '{groups_create}'
    test    : 0
  - comment : Дневник 0 1
    name    : is_diary
    value   : '{is_diary}'
    test    : 0
  - comment : Автор Дневника
    name    : diary_author
    value   : '{diary_author}'
    test    : Новиков 


 
- comment: Удалить трансляцию с идентификатором id
  methods: 
  - GET
  - DELETE
  path: /delete-broadcast/{id}
  example: /delete-broadcast/777
  controller: DeleteBroadcast

# Общие ---------------------------------------------------

- comment: Стартовая страница
  methods: [GET, HEAD]
  path: /
  example: /
  controller: LandingPage

- comment: JSON  маршрутов.  Документация API.
  methods: [GET, HEAD]
  path: /routes
  example: /routes
  controller: GetRoutes


# Фронтэнд ---------------------------------------------------  


- comment: Список трансляций
  methods: [GET, HEAD]
  path: /broadcasts
  example: /broadcasts
  controller: GetBroadcasts

- comment: Трасляция с идентификатором id и ее постами
  methods: [GET, HEAD]
  path: /full-broadcast/{id}
  example: /full-broadcast/354
  controller: GetFullBroadcast

- comment: Посты трансляции с идентификатором id
  methods: [GET, HEAD]
  path: /posts/{id}
  example: /posts/354
  controller: GetPosts

- comment: Ответы к посту с идентификатором id
  methods: [GET, HEAD]
  path: /answers/{id}
  example: /answers/23932
  controller: GetAnswers

- comment: Медиа записи поста с идентификатором id
  methods: [GET, HEAD]
  path: /media/{id}
  example: /media/23932
  controller: GetMedia

- comment: Трасляция с идентификатором id и ее постами. Legacy
  methods: [GET, HEAD]
  path: /api/online.php
  example: /api/online.php
  controller: GetFullBroadcastLegacy
  params:
  - comment: Идентификатор трансляции
    name: id
    value: '{id}'
    test: 354

- comment: Список трансляций.Legacy
  methods: [GET, HEAD]
  path: /api/
  example: /api/?main=0&active=0&num=3
  controller: GetBroadcastList
  params:
  - comment: Основная {0|1}
    name: main
    value: '{main}'
    
  - comment: Активность {0|1}
    name: active
    value: '{active}'
  - comment: Номер
    name: num
    value: '{num}'