
# GraphQL --------------------------------------------------

- comment   : |-
    GraphQL. Получение информации о типах GraphQL.
  methods   :
  - POST
  - GET    
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      query {
        broadcast: __type(name: "Broadcast") {
          name description
          fields {
            name description
            type {
              name 
            }
          }
        }

        post: __type(name: "Post") {
          name description
          fields {
            name description
            type {
              name 
            }
          }
        }

        medium: __type(name: "Medium") {
          name description
          fields {
            name description
            type {
              name 
            }
          }
        }
      }

  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 



- comment   : GraphQL. Получить записи по идентификаторам.
  methods   :
  - POST
  - GET    
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      query {
        broadcast (id: 354) { id  title  time_created link_article }
        post(id:23952){id id_parent text author}
        medium(id:5330){id uri thumb source}
      }
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 


- comment   : GraphQL create
  methods   :
  - POST
  - GET    
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      mutation {
        createBroadcast(
          title:"new broadcast1", 
          time_created: 123, 
          link_article:"link2"
        ) 
        {
          id title 
          time_created 
          time_begin 
          link_article
        }
      }
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 

- comment   : GraphQL update
  methods   :
  - POST
  - GET    
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      mutation {
        updateBroadcast(
          id: 1020,
          title:"updated broadcast 22", 
          time_created: 124, 
          link_article:"updated link2"
        ) 
        {
          id title 
          time_created 
          time_begin 
          link_article
        }
      }  
      
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 


- comment   : GraphQL delete
  methods   :
  - POST
  - GET    
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      mutation {
        deleteBroadcast(
          id: 1020
        ) 
        {
          id title 
          time_created 
          time_begin 
          link_article
        }
      }  
      
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 



# REST ====================================================================================================================
# REST ====================================================================================================================
# REST ====================================================================================================================
# REST ====================================================================================================================


#  medium ---------------------------------------------------


- comment   : Получить Медиа с идентификатором id
  methods   :
  - GET
  path      : /get/:entity/:id
  example   : /get/medium/5330
  controller: GetEntity

- comment: Создать медиа поста с идентификатором post_id
  methods: 
  - POST
  - GET
  path: /create/:entity/
  example: /create/medium/
  controller: CreateEntity
  params    :
  - comment: идентификатор поста
    name   : post_id
    inptype: number
    value  : '{post_id}'
    test   : 23932
  - comment: URI изображения
    name   : uri
    value  : '{uri}'
    test   : created_image.jpg
  - comment: Уменьшенное изображение
    name   : thumb
    value  : '{thumb}'
    test   : created_thumb.jpg
  - comment: Источник
    name   : source
    value  : '{source}'
    test   : новый телевизор



- comment   : Редактировать Медиа с идентификатором id
  methods   : 
  - PUT
  - GET
  path      : /update/:entity/:id
  example   : /update/medium/5330
  controller: UpdateEntity
  params    :
  - comment: Идентификатор поста
    name   : post_id
    inptype: number
    value  : '{post_id}'
    test   : 23932
  - comment: URI изображения
    name   : uri
    value  : '{uri}'
    test   : updated_image.jpg
  - comment: Уменьшенное изображение
    name   : thumb
    value  : '{thumb}'
    test   : updated_thumb.jpg
  - comment: Источник
    name   : source
    value  : '{source}'
    test   : updated телевизор


- comment   : Удалить Медиа с идентификатором id
  methods   : 
  - DELETE
  - GET
  path      : /delete/:entity/:id
  example   : /delete/medium/5389
  controller: DeleteEntity



# post ------------------------------------------------------------


- comment   : Получить пост с идентификатором id
  methods   : 
  - GET
  path      : /get/:entity/:id
  example   : /get/post/23932
  controller: GetEntity


- comment: Создать пост трансляции с идентификатором id
  methods:
  - POST
  - GET
  path: /create/:entity/
  example: /create/post/
  controller: CreateEntity
  params    :
  - comment : Идентификатор поста если это ответ
    name    : id_parent
    inptype : number
    value   : '{id_parent}'
    test    : 0
  - comment : Идентификатор трансляции
    name    : id_broadcast
    inptype : number
    value   : '{id_broadcast}'
    test    : 354
  - comment : Текст поста
    name    : text
    value   : '{text}'
    test    : Текст поста
  - comment : Время поста в формате UNIX
    name    : post_time
    inptype : number
    value   : '{post_time}'
    test    : 1528376820
  - comment : Тип поста 1,2,3,4...
    name    : post_type
    inptype : number
    value   : '{post_type}'
    test    : 3
  - comment : Ссылка
    name    : link
    value   : '{link}'
    test    : http://google.com
  - comment : Есть ли большое изображение 0,1
    name    : has_big_img
    inptype : number
    value   : '{has_big_img}'
    test    : 0
  - comment : ФИО автора поста
    name    : author
    test    : Сидор Пупкин
    value   : '{author}'



- comment   : Редактировать Пост с идентификатором id
  methods   : 
  - PUT
  - GET
  path      : /update/:entity/:id
  example   : /update/post/30001
  controller: UpdateEntity
  params    :
  - comment : Идентификатор поста если это ответ
    name    : id_parent
    inptype : number
    value   : '{id_parent}'
    test    : 
  - comment : Идентификатор трансляции
    name    : id_broadcast
    inptype : number
    value   : '{id_broadcast}'
    test    : 354
  - comment : Текст поста
    name    : text
    value   : '{text}'
    test    : Текст поста
  - comment : Время поста в формате UNIX
    name    : post_time
    inptype : number
    value   : '{post_time}'
    test    : 1528376820
  - comment : Тип поста 1,2,3,4...
    name    : post_type
    inptype : number
    value   : '{post_type}'
    test    : 3
  - comment : Ссылка
    name    : link
    value   : '{link}'
    test    : http://google.com
  - comment : Есть ли большое изображение 0,1
    name    : has_big_img
    inptype : number
    value   : '{has_big_img}'
    test    : 0
  - comment : ФИО автора поста
    name    : author
    test    : Сидор Пупкин
    value   : '{author}'



- comment   : Удалить Пост с идентификаторомid
  methods   :
  - DELETE
  - GET
  path      : /delete/:entity/:id
  example   : /delete/post/30001
  controller: DeleteEntity




#  broadcast ---------------------------------------------------

- comment   : Получить трансляцию с идентификатором id
  methods   : 
  - GET
  path      : /get/:entity/:id
  example   : /get/broadcast/354
  controller: GetEntity


- comment: Создать трансляцию
  methods: 
  - POST
  - GET
  path: /create/:entity/
  example: /create/broadcast/
  controller: CreateEntity
  params    :
  - comment : Название трансляции
    name    : title
    value   : '{title}'
    test    : Новая трансляция
  - comment : Время создания
    name    : time_created
    inptype : number
    value   : '{time_created}'
    test    : 1528376820
  - comment : Время начала
    name    : time_begin
    inptype : number
    value   : '{time_begin}'
    test    : 1528376820
  - comment : Завершена 0 1
    name    : is_ended
    inptype : number
    value   : '{is_ended}'
    test    : 1
  - comment : Показывать дату 0 1
    name    : show_date
    inptype : number
    value   : '{show_date}'
    test    : 1
  - comment : Показывать время 0 1
    name    : show_time
    inptype : number
    value   : '{show_time}'
    test    : 0
  - comment : Яндекс трансляция 0 1
    name    : is_yandex
    inptype : number
    value   : '{is_yandex}'
    test    : 0
  - comment : Идентификаторы Яндекс трансляций
    name    : yandex_ids
    value   : '{yandex_ids}'
    test    : 2, 333, 555
  - comment : Показывать на главной странице 0 1
    name    : show_main_page
    inptype : number
    value   : '{show_main_page}'
    test    : 0
  - comment : Ссылка
    name    : link_article
    value   : '{link_article}'
    test    : http://www.rg.ru/2013/08/09/zhrebiy-site-anons.html
  - comment : Ссылка на изображение
    name    : link_img
    value   : '{link_img}'
    test    : //cdnimg.rg.ru/pril/article/126/55/62/lukjanov-zavrazhin100.jpg
  - comment : groups_create
    name    : groups_create
    inptype : number
    value   : '{groups_create}'
    test    : 0
  - comment : Дневник 0 1
    name    : is_diary
    inptype : number
    value   : '{is_diary}'
    test    : 0
  - comment : Автор Дневника
    name    : diary_author
    value   : '{diary_author}'
    test    : Новиков 

 
- comment: Редактировать трансляцию с идентификатором id
  methods:
  - PUT
  - GET
  path: /update/:entity/:id
  example: /update/broadcast/354
  controller: UpdateEntity
  params    :
  - comment : Название трансляции
    name    : title
    value   : '{title}'
    test    : Обновленная трансляция
  - comment : Время создания
    name    : time_created
    inptype : number
    value   : '{time_created}'
    test    : 1528376820
  - comment : Время начала
    name    : time_begin
    inptype : number
    value   : '{time_begin}'
    test    : 1528376820
  - comment : Завершена 0 1
    name    : is_ended
    inptype : number
    value   : '{is_ended}'
    test    : 1
  - comment : Показывать дату 0 1
    name    : show_date
    inptype : number
    value   : '{show_date}'
    test    : 1
  - comment : Показывать время 0 1
    name    : show_time
    inptype : number
    value   : '{show_time}'
    test    : 0
  - comment : Яндекс трансляция 0 1
    name    : is_yandex
    inptype : number
    value   : '{is_yandex}'
    test    : 0
  - comment : Идентификаторы Яндекс трансляций
    name    : yandex_ids
    value   : '{yandex_ids}'
    test    : 2, 333, 555
  - comment : Показывать на главной странице 0 1
    name    : show_main_page
    inptype : number
    value   : '{show_main_page}'
    test    : 0
  - comment : Ссылка
    name    : link_article
    value   : '{link_article}'
    test    : http://www.rg.ru/2013/08/09/zhrebiy-site-anons.html
  - comment : Ссылка на изображение
    name    : link_img
    value   : '{link_img}'
    test    : //cdnimg.rg.ru/pril/article/126/55/62/lukjanov-zavrazhin100.jpg
  - comment : groups_create
    name    : groups_create
    inptype : number
    value   : '{groups_create}'
    test    : 0
  - comment : Дневник 0 1
    name    : is_diary
    inptype : number
    value   : '{is_diary}'
    test    : 0
  - comment : Автор дневника
    name    : diary_author
    value   : '{diary_author}'
    test    : Новиков 


 
- comment: Удалить трансляцию с идентификатором id
  methods: 
  - DELETE
  - GET
  path: /delete/:entity/:id
  example: /delete/broadcast/777
  controller: DeleteEntity



# COMMON ====================================================================================================================
# COMMON ====================================================================================================================
# COMMON ====================================================================================================================
# COMMON ====================================================================================================================




# Общие ---------------------------------------------------

- comment: Стартовая страница
  methods: [GET]
  path: /
  example: /
  controller: LandingPage

- comment: JSON  маршрутов.  Документация API.
  methods: [GET]
  path: /routes
  example: /routes
  controller: GetRoutes





# FRONTEND ====================================================================================================================
# FRONTEND ====================================================================================================================
# FRONTEND ====================================================================================================================
# FRONTEND ====================================================================================================================



# Фронтэнд ---------------------------------------------------  


- comment: Список трансляций
  methods: [GET]
  path: /api/broadcasts
  example: /api/broadcasts
  controller: GetBroadcasts

- comment: Трасляция с идентификатором id и ее постами
  methods: [GET]
  path: /api/full-broadcast/:id
  example: /api/full-broadcast/354
  controller: GetFullBroadcast

- comment: Посты трансляции с идентификатором id
  methods: [GET]
  path: /api/posts/:id
  example: /api/posts/354
  controller: GetPosts

- comment: Ответы к посту с идентификатором id
  methods: [GET]
  path: /api/answers/:id
  example: /api/answers/23932
  controller: GetAnswers

- comment: Медиа для поста с идентификатором id
  methods: [GET]
  path: /api/media/:id
  example: /api/media/23932
  controller: GetMedia

- comment: Трасляция с идентификатором id и ее постами. Legacy
  methods: [GET]
  path: /api/online.php
  example: /api/online.php
  controller: GetFullBroadcastLegacy
  params:
  - comment: Идентификатор трансляции
    name: id
    inptype : number
    value: ':id'
    test: 354

- comment: Список трансляций.Legacy
  methods: [GET, HEAD]
  path: /api/
  example: /api/?main=0&active=0&num=3
  controller: GetBroadcastList
  params:
  - comment: Основная {0|1}
    name: main
    inptype : number
    value: '{main}'
    test: 0
  - comment: Активность {0|1}
    name: active
    inptype : number
    value: '{active}'
    test: 0
  - comment: Номер
    name: num
    inptype : number
    value: '{num}'
    test: 3