# - comment   : |-
#     GraphQL. Префлайт запрос. 
#   methods   :
#   - OPTIONS  
#   path      : /graphql
#   example   : /graphql
#   controller: PingHandler



# GraphQL --------------------------------------------------
- comment   : |-
    <b>Загрузка</b> 
    Заполните форму выше.
    Поле запроса скрыто по умолчанию из за медленного рендеринга.


  methods   :
  - POST
  - GET    
   
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      mutation {
        create_medium(


          ) 
          {



          }
        }	




# - comment   : |-
#     <b>GraphQL.</b> Получение информации о типах GraphQL.
#   methods   :
#   - POST
#   - GET    
   
#   path      : /graphql
#   example   : /graphql
#   controller: GraphQL
#   params    :
#   - comment: запрос
#     name   : query
#     value  : '{query}'
#     test   : |- 
#       query {
#         broadcast: __type(name: "Broadcast") {
#           name description
#           fields {
#             name description
#             type {
#               name 
#             }
#           }
#         }

#         post: __type(name: "Post") {
#           name description
#           fields {
#             name description
#             type {
#               name 
#             }
#           }
#         }

#         medium: __type(name: "Medium") {
#           name description
#           fields {
#             name description
#             type {
#               name 
#             }
#           }
#         }
#       }

#   - comment: переменные
#     name   : variables
#     value  : '{variables}'
#     test   : '{}' 


# - comment   : <b>broadcasts(...)</b> Получить список трансляций.
#   methods   :
#   - POST
#   - GET    
   
#   path      : /graphql
#   example   : /graphql
#   controller: GraphQL
#   params    :
#   - comment: запрос
#     name   : query
#     value  : '{query}'
#     test   : |- 
#       query {
#           broadcasts(search:"красный") { id  title link_article is_ended }  
#       }
#   - comment: переменные
#     name   : variables
#     value  : '{variables}'
#     test   : '{}' 


- comment   : <b>list_broadcast(...)</b> Получить список трансляций и их количество.
  methods   :
  - POST
  - GET    
   
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      query{
        list_broadcast(search: "жеребьевка" ){
          length
          list {
            id
            title
          } 
        }
      }
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 


- comment   : <b>get_broadcast(id)</b>. Получить трансляцию по идентификатору
  methods   :
  - POST
  - GET    
   
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      query {
        get_broadcast (id: 354) { id  title  time_created link_article }
      }
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 



- comment   : <b>get_broadcast_posts(id_broadcast)</b> Получить посты трансляции по ее идентификатору.
  methods   :
  - POST
  - GET    
   
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      query {
        get_broadcast_posts(id_broadcast: 354) { id id_broadcast text author}
      }
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 



- comment   : <b>get_post_media(post_id)</b> Получить медиа поста по его идентификатору.
  methods   :
  - POST
  - GET    
   
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      query {
        get_post_media(post_id: 23932) { id uri source}
      }
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 


- comment   : <b>get_post_answers(id_parent)</b> Получить ответы к посту по его идентификатору.
  methods   :
  - POST
  - GET    
   
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      query {
        get_post_answers(id_parent: 23932) { 
          id 
          id_broadcast 
          text 
          author
          }
      }
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 



- comment   : <b>get_post(id)</b> Получить пост по идентификатору
  methods   :
  - POST
  - GET   
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      query {
        get_post(id:23952){id id_parent text author}
      }
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 


- comment   : <b>get_medium(id)</b> Получить медиа по идентификатору
  methods   :
  - POST
  - GET    
   
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      query {
        get_medium(id:5330){id uri thumb source}
      }
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 



- comment   : <b>create_broadcast(...)</b> Породить трансляцию
  methods   :
  - POST
  - GET    
   
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      mutation {
        create_broadcast(
          title:"new broadcast1", 
          time_created: 123, 
          link_article:"link2"
        ) 
        {
          id title 
          time_created 
          time_begin 
          link_article
        }
      }
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 



- comment   : <b>update_broadcast(...)</b> Обновить трансляцию
  methods   :
  - POST
  - GET    
   
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      mutation {
        update_broadcast(
          id: 1000,
          title:"updated broadcast 22", 
          time_created: 124, 
          link_article:"updated link2"
        ) 
        {
          id title 
          time_created 
          time_begin 
          link_article
        }
      }  
      
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 


- comment   : <b>delete_broadcast(id)</b> Удалить трансляцию
  methods   :
  - POST
  - GET    
   
  path      : /graphql
  example   : /graphql
  controller: GraphQL
  params    :
  - comment: запрос
    name   : query
    value  : '{query}'
    test   : |- 
      mutation {
        delete_broadcast(
          id: 1000
        ) 
        {
          id title 
          time_created 
          time_begin 
          link_article
        }
      }  
      
  - comment: переменные
    name   : variables
    value  : '{variables}'
    test   : '{}' 



# REST ====================================================================================================================
# REST ====================================================================================================================
# REST ====================================================================================================================
# REST ====================================================================================================================


# #  medium ---------------------------------------------------

# - comment   : Получить Медиа с идентификатором id
#   methods   :
#   - GET
#   path      : /get/:entity/:id
#   example   : /get/medium/5330
#   controller: GetEntity

# # post ------------------------------------------------------------

# - comment   : Получить пост с идентификатором id
#   methods   : 
#   - GET
#   path      : /get/:entity/:id
#   example   : /get/post/23932
#   controller: GetEntity


# #  broadcast ---------------------------------------------------

# - comment   : Получить трансляцию с идентификатором id
#   methods   : 
#   - GET
#   path      : /get/:entity/:id
#   example   : /get/broadcast/354
#   controller: GetEntity





# COMMON ====================================================================================================================
# COMMON ====================================================================================================================
# COMMON ====================================================================================================================
# COMMON ====================================================================================================================




# Общие ---------------------------------------------------

# - comment: Стартовая страница
#   methods: [GET]
#   path: /
#   example: /
#   controller: LandingPage

# - comment: JSON  маршрутов.  Документация API.
#   methods: [GET]
#   path: /routes
#   example: /routes
#   controller: GetRoutes





# FRONTEND ====================================================================================================================
# FRONTEND ====================================================================================================================
# FRONTEND ====================================================================================================================
# FRONTEND ====================================================================================================================



# Фронтэнд ---------------------------------------------------  


- comment: Список трансляций
  methods: [GET]
  path: /api/broadcasts
  example: /api/broadcasts
  controller: GetBroadcasts

- comment: Трансляция с идентификатором id и ее постами
  methods: [GET]
  path: /api/full-broadcast/:id
  example: /api/full-broadcast/354
  controller: GetFullBroadcast

- comment: Посты трансляции с идентификатором id
  methods: [GET]
  path: /api/posts/:id
  example: /api/posts/354
  controller: GetPosts

- comment: Ответы к посту с идентификатором id
  methods: [GET]
  path: /api/answers/:id
  example: /api/answers/23932
  controller: GetAnswers

- comment: Медиа для поста с идентификатором id
  methods: [GET]
  path: /api/media/:id
  example: /api/media/23932
  controller: GetMedia

- comment: Трансляция с идентификатором id и ее постами. Legacy
  methods: [GET]
  path: /api/online.php
  example: /api/online.php
  controller: GetFullBroadcastLegacy
  params:
  - comment: Идентификатор трансляции
    name: id
    inptype : number
    value: ':id'
    test: 354

- comment: Список трансляций.Legacy
  methods: [GET, HEAD]
  path: /api/
  example: /api/?main=0&active=0&num=3
  controller: GetBroadcastList
  params:
  - comment: Основная {0|1}
    name: main
    inptype : number
    value: '{main}'
    test: 0
  - comment: Активность {0|1}
    name: active
    inptype : number
    value: '{active}'
    test: 0
  - comment: Номер
    name: num
    inptype : number
    value: '{num}'
    test: 3